defaults: &defaults
  docker:
    - image: circleci/node:10.16.3

version: 2
jobs:
  deploy-on-build:
    <<: *defaults

    steps:
      - checkout

      - run:
          name: Set configuration
          command: git config --global user.email "$GITHUB_AUTHOR_EMAIL" && git config --global user.name "$GITHUB_AUTHOR_NAME"

      - run:
          name: Pull changes
          command: git pull --tags origin build

      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: Write Azure DevOps NPM Token to ~/.npmrc
          command:
            printf "registry=https://pkgs.dev.azure.com/Silevis/ReactGrid/_packaging/ReactGrid-artifacts-feed/npm/registry/\n
            always-auth=true\n\n

            ; begin auth token\n
            //pkgs.dev.azure.com/Silevis/ReactGrid/_packaging/ReactGrid-artifacts-feed/npm/registry/:username=Silevis\n
            //pkgs.dev.azure.com/Silevis/ReactGrid/_packaging/ReactGrid-artifacts-feed/npm/registry/:_password=[$BASE64_ENCODED_PERSONAL_ACCESS_TOKEN]\n
            //pkgs.dev.azure.com/Silevis/ReactGrid/_packaging/ReactGrid-artifacts-feed/npm/registry/:email=patryk.eliasz@silevis.com\n
            //pkgs.dev.azure.com/Silevis/ReactGrid/_packaging/ReactGrid-artifacts-feed/npm/:username=Silevis\n
            //pkgs.dev.azure.com/Silevis/ReactGrid/_packaging/ReactGrid-artifacts-feed/npm/:_password=[$BASE64_ENCODED_PERSONAL_ACCESS_TOKEN]\n
            //pkgs.dev.azure.com/Silevis/ReactGrid/_packaging/ReactGrid-artifacts-feed/npm/:email=patryk.eliasz@silevis.com\n
            ; end auth token" >> .npmrc

      - run:
          name: Install ReactGrid Pro
          command: npm install @silevis/reactgrid@latest --no-save

      - run:
          name: Run build:tsc
          command: npm run build:tsc

      - run:
          name: Chmod scripts/copyStyles.sh
          command: chmod +x ./scripts/copyStyles.sh

      - run:
          name: Run ./copyStyles.sh
          command: sh ./scripts/copyStyles.sh

      - run:
          name: Add changes
          command: git add -A

      - run:
          name: Commit updated package version
          command: git commit -m "upgrade version [ci skip]"

      - run:
          name: Push upgraded version
          command: git push https://$GITHUB_TOKEN@github.com/silevis/reactgrid-samples.git build

workflows:
  version: 2
  main:
    jobs:
      - deploy-on-build:
          filters:
            branches:
              only: build
